#!/bin/bash

#PBS -q dm
#PBS -N drexm        
#PBS -l walltime=24:00:00
# For distributed memory machine
#PBS -l nodes=4:ppn=1:ncpus=28
# For shared memory machine
# PBS -l nodes=1:ppn=2:ncpus=28   
#PBS -l mem=100gb

# set path of wroking directory
cd $PBS_O_WORKDIR

# set number of threads     
export OMP_NUM_THREADS=28  

mpirun -np 4 ./drex_m drexm_input_3Dbox.dat
#mpirun -np 2 ./drex_m drexm_input_poulami.dat

# mpirun -np 2 ./drex_m ../cookbooks/2Dcartesian_convection/drexm_input.dat
# mpirun -np 8 ./drex_m ../cookbooks/2Dpolar_convection/drexm_input.dat
# mpirun -np 8 ./drex_m ../cookbooks/2Dpolar_subduction/drexm_input.dat
# mpirun -np 8 ./drex_m ../cookbooks/3Dcartesian_sinkingslab/drexm_input.dat
# mpirun -np 8 ./drex_m ../cookbooks/3Dspherical_sinkingslab/drexm_input.dat
# mpirun -np 16 ./drex_m ../cookbooks/3Dspherical_global/drexm_input.dat
